services:
  redis:
    image: redis:alpine
    container_name: prod-redis
    env_file:
      - ../.env
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOST=${REDIS_HOST}
    ports:
      - "6379:6379"